SELECT 
    D.DEPARTMENT_NAME AS DEPARTMENT,
    COUNT(U.ID) AS EMPLOYEE_COUNT,
    AVG(U.SALARY) AS AVERAGE_SALARY
FROM 
    Department D
JOIN 
    Users U ON D.ID = U.DEPARTMENT_ID
GROUP BY 
    D.DEPARTMENT_NAME;
